###  1. create member
POST http://localhost:8080/members
Content-Type: application/json
Accept: application/json

{
  "createdAt": "2024-07-07 09:00:00",
  "updatedAt": "2024-07-07 09:00:00",
  "loginType": "COMMON",
  "useYn": "Y",
  "auth": "MEMBER",
  "username": "minjae123",
  "password": "password123",
  "nickname": "nickminjae",
  "name": "kim minjae",
  "email": "min356812@naver.com"
}

###  1. create member
GET http://localhost:8080/bible?book=1&chapter=1
Content-Type: application/json
Accept: application/json

